/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BoardRouteImport } from './routes/board'
import { Route as BriefRouteImport } from './routes/brief'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as FantasyRouteImport } from './routes/fantasy'
import { Route as GymRouteImport } from './routes/gym'
import { Route as KeepersRouteImport } from './routes/keepers'
import { Route as MockRouteImport } from './routes/mock'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SlateRouteImport } from './routes/slate'
import { Route as TapeRouteImport } from './routes/tape'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as WallRouteImport } from './routes/wall'
import { Route as Games160RouteImport } from './routes/games.16-0'
import { Route as Games820RouteImport } from './routes/games.82-0'
import { Route as GamesCornersRouteImport } from './routes/games.corners'
import { Route as GamesDailyRouteImport } from './routes/games.daily'
import { Route as GamesGoatRouteImport } from './routes/games.goat'
import { Route as WalkIdRouteImport } from './routes/walk.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefRoute = BriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasyRoute = FantasyRouteImport.update({
  id: '/fantasy',
  path: '/fantasy',
  getParentRoute: () => rootRouteImport,
} as any)
const GymRoute = GymRouteImport.update({
  id: '/gym',
  path: '/gym',
  getParentRoute: () => rootRouteImport,
} as any)
const KeepersRoute = KeepersRouteImport.update({
  id: '/keepers',
  path: '/keepers',
  getParentRoute: () => rootRouteImport,
} as any)
const MockRoute = MockRouteImport.update({
  id: '/mock',
  path: '/mock',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SlateRoute = SlateRouteImport.update({
  id: '/slate',
  path: '/slate',
  getParentRoute: () => rootRouteImport,
} as any)
const TapeRoute = TapeRouteImport.update({
  id: '/tape',
  path: '/tape',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const WallRoute = WallRouteImport.update({
  id: '/wall',
  path: '/wall',
  getParentRoute: () => rootRouteImport,
} as any)
const Games160Route = Games160RouteImport.update({
  id: '/games/16-0',
  path: '/games/16-0',
  getParentRoute: () => rootRouteImport,
} as any)
const Games820Route = Games820RouteImport.update({
  id: '/games/82-0',
  path: '/games/82-0',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCornersRoute = GamesCornersRouteImport.update({
  id: '/games/corners',
  path: '/games/corners',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDailyRoute = GamesDailyRouteImport.update({
  id: '/games/daily',
  path: '/games/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGoatRoute = GamesGoatRouteImport.update({
  id: '/games/goat',
  path: '/games/goat',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkIdRoute = WalkIdRouteImport.update({
  id: '/walk/$id',
  path: '/walk/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRoute
  '/brief': typeof BriefRoute
  '/changelog': typeof ChangelogRoute
  '/fantasy': typeof FantasyRoute
  '/gym': typeof GymRoute
  '/keepers': typeof KeepersRoute
  '/mock': typeof MockRoute
  '/shop': typeof ShopRoute
  '/slate': typeof SlateRoute
  '/tape': typeof TapeRoute
  '/trade': typeof TradeRoute
  '/wall': typeof WallRoute
  '/games/16-0': typeof Games160Route
  '/games/82-0': typeof Games820Route
  '/games/corners': typeof GamesCornersRoute
  '/games/daily': typeof GamesDailyRoute
  '/games/goat': typeof GamesGoatRoute
  '/walk/$id': typeof WalkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRoute
  '/brief': typeof BriefRoute
  '/changelog': typeof ChangelogRoute
  '/fantasy': typeof FantasyRoute
  '/gym': typeof GymRoute
  '/keepers': typeof KeepersRoute
  '/mock': typeof MockRoute
  '/shop': typeof ShopRoute
  '/slate': typeof SlateRoute
  '/tape': typeof TapeRoute
  '/trade': typeof TradeRoute
  '/wall': typeof WallRoute
  '/games/16-0': typeof Games160Route
  '/games/82-0': typeof Games820Route
  '/games/corners': typeof GamesCornersRoute
  '/games/daily': typeof GamesDailyRoute
  '/games/goat': typeof GamesGoatRoute
  '/walk/$id': typeof WalkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/board': typeof BoardRoute
  '/brief': typeof BriefRoute
  '/changelog': typeof ChangelogRoute
  '/fantasy': typeof FantasyRoute
  '/gym': typeof GymRoute
  '/keepers': typeof KeepersRoute
  '/mock': typeof MockRoute
  '/shop': typeof ShopRoute
  '/slate': typeof SlateRoute
  '/tape': typeof TapeRoute
  '/trade': typeof TradeRoute
  '/wall': typeof WallRoute
  '/games/16-0': typeof Games160Route
  '/games/82-0': typeof Games820Route
  '/games/corners': typeof GamesCornersRoute
  '/games/daily': typeof GamesDailyRoute
  '/games/goat': typeof GamesGoatRoute
  '/walk/$id': typeof WalkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/board'
    | '/brief'
    | '/changelog'
    | '/fantasy'
    | '/gym'
    | '/keepers'
    | '/mock'
    | '/shop'
    | '/slate'
    | '/tape'
    | '/trade'
    | '/wall'
    | '/games/16-0'
    | '/games/82-0'
    | '/games/corners'
    | '/games/daily'
    | '/games/goat'
    | '/walk/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/board'
    | '/brief'
    | '/changelog'
    | '/fantasy'
    | '/gym'
    | '/keepers'
    | '/mock'
    | '/shop'
    | '/slate'
    | '/tape'
    | '/trade'
    | '/wall'
    | '/games/16-0'
    | '/games/82-0'
    | '/games/corners'
    | '/games/daily'
    | '/games/goat'
    | '/walk/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/board'
    | '/brief'
    | '/changelog'
    | '/fantasy'
    | '/gym'
    | '/keepers'
    | '/mock'
    | '/shop'
    | '/slate'
    | '/tape'
    | '/trade'
    | '/wall'
    | '/games/16-0'
    | '/games/82-0'
    | '/games/corners'
    | '/games/daily'
    | '/games/goat'
    | '/walk/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BoardRoute: typeof BoardRoute
  BriefRoute: typeof BriefRoute
  ChangelogRoute: typeof ChangelogRoute
  FantasyRoute: typeof FantasyRoute
  GymRoute: typeof GymRoute
  KeepersRoute: typeof KeepersRoute
  MockRoute: typeof MockRoute
  ShopRoute: typeof ShopRoute
  SlateRoute: typeof SlateRoute
  TapeRoute: typeof TapeRoute
  TradeRoute: typeof TradeRoute
  WallRoute: typeof WallRoute
  Games160Route: typeof Games160Route
  Games820Route: typeof Games820Route
  GamesCornersRoute: typeof GamesCornersRoute
  GamesDailyRoute: typeof GamesDailyRoute
  GamesGoatRoute: typeof GamesGoatRoute
  WalkIdRoute: typeof WalkIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief': {
      id: '/brief'
      path: '/brief'
      fullPath: '/brief'
      preLoaderRoute: typeof BriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy': {
      id: '/fantasy'
      path: '/fantasy'
      fullPath: '/fantasy'
      preLoaderRoute: typeof FantasyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym': {
      id: '/gym'
      path: '/gym'
      fullPath: '/gym'
      preLoaderRoute: typeof GymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keepers': {
      id: '/keepers'
      path: '/keepers'
      fullPath: '/keepers'
      preLoaderRoute: typeof KeepersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock': {
      id: '/mock'
      path: '/mock'
      fullPath: '/mock'
      preLoaderRoute: typeof MockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slate': {
      id: '/slate'
      path: '/slate'
      fullPath: '/slate'
      preLoaderRoute: typeof SlateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tape': {
      id: '/tape'
      path: '/tape'
      fullPath: '/tape'
      preLoaderRoute: typeof TapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wall': {
      id: '/wall'
      path: '/wall'
      fullPath: '/wall'
      preLoaderRoute: typeof WallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/16-0': {
      id: '/games/16-0'
      path: '/games/16-0'
      fullPath: '/games/16-0'
      preLoaderRoute: typeof Games160RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/82-0': {
      id: '/games/82-0'
      path: '/games/82-0'
      fullPath: '/games/82-0'
      preLoaderRoute: typeof Games820RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/corners': {
      id: '/games/corners'
      path: '/games/corners'
      fullPath: '/games/corners'
      preLoaderRoute: typeof GamesCornersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/daily': {
      id: '/games/daily'
      path: '/games/daily'
      fullPath: '/games/daily'
      preLoaderRoute: typeof GamesDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/goat': {
      id: '/games/goat'
      path: '/games/goat'
      fullPath: '/games/goat'
      preLoaderRoute: typeof GamesGoatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walk/$id': {
      id: '/walk/$id'
      path: '/walk/$id'
      fullPath: '/walk/$id'
      preLoaderRoute: typeof WalkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BoardRoute: BoardRoute,
  BriefRoute: BriefRoute,
  ChangelogRoute: ChangelogRoute,
  FantasyRoute: FantasyRoute,
  GymRoute: GymRoute,
  KeepersRoute: KeepersRoute,
  MockRoute: MockRoute,
  ShopRoute: ShopRoute,
  SlateRoute: SlateRoute,
  TapeRoute: TapeRoute,
  TradeRoute: TradeRoute,
  WallRoute: WallRoute,
  Games160Route: Games160Route,
  Games820Route: Games820Route,
  GamesCornersRoute: GamesCornersRoute,
  GamesDailyRoute: GamesDailyRoute,
  GamesGoatRoute: GamesGoatRoute,
  WalkIdRoute: WalkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
